services:
  web:
    build:
      context: ./php-web
      dockerfile: Dockerfile
    container_name: web-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./php-web:/var/www/html
    environment:
      - NODE_API_URL=http://node_api:5000
    depends_on:
      - node_api
  
  node_api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    container_name: node-api
    volumes:
      - ./node-api:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
       DB_HOST: db
       DB_PORT: 3306
       DB_USER: root
       DB_PASSWORD: root
       DB_NAME: hackathon
  db:
    image: mysql:8.0
    container_name: dbHackathon
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: database-acess
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  database: